/*
 *  UCF COP3330 Summer 2021 Assignment 3 Solutions
 *  Copyright 2021 Kevin Schiffli
 */
@startuml
'https://plantuml.com/class-diagram

Class App {
--Inputs--
+getDataFromFile
+getProduct(List<Product>)
--Outputs--
-printOutput(List<Product>)
}

Class ProductSearch {
--Computations--
searchProducts(String, List<Product>)
}

Object Product{
name
price
quantity
}

App -> ProductSearch
@enduml